sudo: required
language: cpp
services: docker
notifications:
  email:
    on_success: change
    on_failure: always
env:
  matrix:
    - ROOT_VERSION=root_v6.08.00.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
before_install:
  # install cmake and gtest
  - sudo apt-get install cmake libgtest-dev libglu1-mesa
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  # install root
  - wget https://root.cern.ch/download/${ROOT_VERSION}
  - tar xzf ${ROOT_VERSION}
  - source root/bin/thisroot.sh
install:
  # Install Eigen from source
  - wget https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz -O /tmp/eigen.tar.gz
  - mkdir eigen3-src && tar -xzf /tmp/eigen.tar.gz -C eigen3-src --strip 1
  - cd eigen3-src && mkdir build && cd build && cmake .. && sudo make install && cd ../..
  # create dedicated build folder
  - cd .. && mkdir build && cd build
  - cmake ../GenFit
  - make
  - make tests
script:
  # generate test geometry
  - cd bin
  - root -l -b -q ../../GenFit/test/makeGeom.C
  # run unit tests
  - ./gtests
  - ./unitTests

